// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: latest_availabilities.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addLatestAvailability = `-- name: AddLatestAvailability :exec
INSERT INTO latest_availabilities (
    tour_uuid,
    recorded_at,
    availability_date,
    raw_data
) VALUES (?, CURRENT_TIMESTAMP, ?, ?)
`

type AddLatestAvailabilityParams struct {
	TourUuid         uuid.UUID
	AvailabilityDate time.Time
	RawData          string
}

func (q *Queries) AddLatestAvailability(ctx context.Context, arg AddLatestAvailabilityParams) error {
	_, err := q.db.ExecContext(ctx, addLatestAvailability, arg.TourUuid, arg.AvailabilityDate, arg.RawData)
	return err
}

const getLatestAvailability = `-- name: GetLatestAvailability :one
SELECT tour_uuid, recorded_at, availability_date, raw_data FROM latest_availabilities
WHERE tour_uuid = ? ORDER BY availability_date DESC LIMIT 1
`

func (q *Queries) GetLatestAvailability(ctx context.Context, tourUuid uuid.UUID) (LatestAvailability, error) {
	row := q.db.QueryRowContext(ctx, getLatestAvailability, tourUuid)
	var i LatestAvailability
	err := row.Scan(
		&i.TourUuid,
		&i.RecordedAt,
		&i.AvailabilityDate,
		&i.RawData,
	)
	return i, err
}
