// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type LatestAvailability struct {
	TourUuid         uuid.UUID
	RecordedAt       time.Time
	AvailabilityDate time.Time
	RawData          string
}

type Tour struct {
	Uuid uuid.UUID
	Name string
	Url  string
}
