// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type LatestAvailability struct {
	TourUuid         interface{}
	RecordedAt       time.Time
	AvailabilityDate time.Time
	RawData          string
}
