// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type LatestAvailability struct {
	TourUuid         interface{}
	RecordedAt       interface{}
	AvailabilityDate interface{}
	RawData          sql.NullString
}
